### ISSUE TITLE
Is there a plan to make a dashboard for clusternet

### ISSUE THREAD

**Issue by chestarss** [clusternet/clusternet#220] opened 2021-12-22 09:20 UTC

**Comment by dixudx** [comment] 2021-12-27 03:29
Duplicate of #87.

Yes, dashboard stays in our plan. And we need more contributors in our community to make this happen ASAP.

**Comment by yiwei-C** [comment] 2023-02-23 09:45
Duplicate of https://github.com/clusternet/clusternet/issues/87.

**Closed by yiwei-C** 2023-02-23 09:45 UTC
Labels: kind/feature
